"""initial blackbook schema

Revision ID: 286eb21295ab
Revises: 
Create Date: 2026-06-07 13:03:04.712604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '286eb21295ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('sleeper_league_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('season', sa.String(length=8), nullable=False),
    sa.Column('total_rosters', sa.Integer(), nullable=False),
    sa.Column('superflex', sa.Boolean(), nullable=False),
    sa.Column('scoring_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roster_positions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sleeper_league_id')
    )
    op.create_table('user_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('league_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=32), nullable=False),
    sa.Column('rankings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.sleeper_league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=32), nullable=False),
    sa.Column('sleeper_player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('nfl_team', sa.String(length=8), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('dynasty_rating', sa.Integer(), nullable=True),
    sa.Column('dynasty_score', sa.Float(), nullable=True),
    sa.Column('dynasty_rookie', sa.Boolean(), nullable=False),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hppg', sa.Float(), nullable=True),
    sa.Column('worp_ppg', sa.Float(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('hppg_expected', sa.Boolean(), nullable=False),
    sa.Column('trade_value', sa.Float(), nullable=True),
    sa.Column('flex_rating', sa.Integer(), nullable=True),
    sa.Column('win_now_rating', sa.Integer(), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.sleeper_league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'sleeper_player_id', name='uq_player_snapshot')
    )
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=32), nullable=False),
    sa.Column('sleeper_roster_id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('is_me', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.sleeper_league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'sleeper_roster_id', name='uq_roster_league_sleeper')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('counts_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.sleeper_league_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('sleeper_player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('nfl_team', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'sleeper_player_id', name='uq_roster_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_players')
    op.drop_table('sync_runs')
    op.drop_table('rosters')
    op.drop_table('player_snapshots')
    op.drop_table('league_snapshots')
    op.drop_table('user_settings')
    op.drop_table('leagues')
    # ### end Alembic commands ###
